package goope

import (
	"math"
	"testing"
)

var defaultKey = []byte("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA") // 32 × 'A'
var smallKey = []byte("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")   // 32 × 'B'

// TestEncryptMatchesPython verifies our output matches the Python reference implementation exactly, using the same key and default ranges.
func TestEncryptMatchesPython(t *testing.T) {
	cipher, err := NewOPE(defaultKey, nil, nil)
	if err != nil {
		t.Fatal(err)
	}

	// Expected values generated by Python reference implementation.
	tests := []struct {
		plaintext  int64
		ciphertext int64
	}{
		{0, 220331},
		{1, 276895},
		{100, 6687907},
		{500, 30565337},
		{1000, 60687481},
		{5000, 318247430},
		{32767, 2147273337},
	}

	for _, tt := range tests {
		got, err := cipher.Encrypt(tt.plaintext)
		if err != nil {
			t.Errorf("Encrypt(%d): unexpected error: %v", tt.plaintext, err)
			continue
		}
		if got != tt.ciphertext {
			t.Errorf("Encrypt(%d) = %d, want %d", tt.plaintext, got, tt.ciphertext)
		}
	}
}

// TestDecryptRoundTrip tests that decrypt(encrypt(x)) == x for all tests values
func TestDecryptRoundTrip(t *testing.T) {
	inRange := ValueRange{Start: -1000, End: int64(math.Pow(2, 20))}
	outRange := ValueRange{Start: -10000, End: int64(math.Pow(2, 32))}
	ope, err := NewOPE(defaultKey, &inRange, &outRange)
	if err != nil {
		t.Fatalf("Failed to create OPE cipher: %v", err)
	}

	for _, pt := range []int64{-1000, -100, -20, -1, 0, 1, 10, 100, 314, 1337, 1338, 10000} {
		ct, err := ope.Encrypt(pt)
		if err != nil {
			t.Fatalf("Encrypt(%d) returned error: %v", pt, err)
		}
		got, err := ope.Decrypt(ct)
		if err != nil {
			t.Fatalf("Decrypt(%d) returned error: %v", ct, err)
		}
		if got != pt {
			t.Fatalf("Decrypt(Encrypt(%d)) = %d; want %d", pt, got, pt)
		}
	}
}

func Ints64AreSorted(a []int64) bool {
	for i := 1; i < len(a); i++ {
		if a[i] < a[i-1] {
			return false
		}
	}
	return true
}

// TestOrderPreserved tests that the order of plaintexts is preserved in the ciphertexts.
func TestOrderPreserved(t *testing.T) {
	ope, err := NewOPE(defaultKey, nil, nil)
	if err != nil {
		t.Fatalf("Failed to create OPE cipher: %v", err)
	}

	plaintexts := []int64{0, 1, 2, 10, 28, 42, 1000, 1001, int64(math.Pow(2, 15) - 1)}
	ciphertexts := make([]int64, len(plaintexts))
	for i, pt := range plaintexts {
		ct, err := ope.Encrypt(pt)
		if err != nil {
			t.Fatalf("Encrypt(%d) returned error: %v", pt, err)
		}
		ciphertexts[i] = ct
	}

	if !Ints64AreSorted(ciphertexts) {
		t.Fatalf("Ciphertexts are not in sorted order: %v", ciphertexts)
	}
}

// TestDeterministic tests that encrypting the same plaintext multiple times yields the same ciphertext.
func TestDeterministic(t *testing.T) {
	ope, err := NewOPE(defaultKey, nil, nil)
	if err != nil {
		t.Fatalf("Failed to create OPE cipher: %v", err)
	}
	plaintexts := []int64{0, 314, 1337, 1338, 10000}
	for _, pt := range plaintexts {
		ct1, err := ope.Encrypt(pt)
		if err != nil {
			t.Fatalf("Encrypt(%d) returned error: %v", pt, err)
		}
		ct2, err := ope.Encrypt(pt)
		if err != nil {
			t.Fatalf("Encrypt(%d) returned error: %v", pt, err)
		}
		if ct1 != ct2 {
			t.Fatalf("Encrypt(%d) returned different ciphertexts: %d and %d", pt, ct1, ct2)
		}
	}
}

// TestDenseRange tests that equal ranges (0..32768) yield 1-1 mappings
func TestDenseRange(t *testing.T) {
	inRange := ValueRange{Start: 0, End: int64(math.Pow(2, 15))}
	outRange := inRange.Copy()
	ope, err := NewOPE(defaultKey, &inRange, &outRange)
	if err != nil {
		t.Fatalf("Failed to create OPE cipher: %v", err)
	}
	plaintexts := []int64{0, 10, 20, 50, 100, 1000, int64(math.Pow(2, 10)), int64(math.Pow(2, 15))}
	for _, pt := range plaintexts {
		ct, err := ope.Encrypt(pt)
		if err != nil {
			t.Fatalf("Encrypt(%d) returned error: %v", pt, err)
		}
		got, err := ope.Decrypt(ct)
		if err != nil {
			t.Fatalf("Decrypt(%d) returned error: %v", ct, err)
		}
		if got != pt {
			t.Fatalf("Decrypt(Encrypt(%d)) = %d; want %d", pt, got, pt)
		}
	}
}

// TestCustomRanges verifies behavior when a small custom range is used (0..9 -> 0..99)
func TestCustomRanges(t *testing.T) {
	in, _ := NewValueRange(0, 9)
	out, _ := NewValueRange(0, 99)
	ope, err := NewOPE(smallKey, &in, &out)
	if err != nil {
		t.Fatalf("Failed to create OPE cipher: %v", err)
	}

	// Expected values generated by Python reference implementation.
	expected := []int64{17, 46, 59, 64, 68, 77, 81, 84, 90, 91}
	for pt, want := range expected {
		got, err := ope.Encrypt(int64(pt))
		if err != nil {
			t.Errorf("Encrypt(%d) returned error: %v", pt, err)
			continue
		}
		if got != want {
			t.Fatalf("Encrypt(%d) = %d; want %d", pt, got, want)
		}
		// also verify round-trip
		back, err := ope.Decrypt(got)
		if err != nil {
			t.Errorf("Decrypt(%d) returned error: %v", got, err)
			continue
		}
		if back != int64(pt) {
			t.Fatalf("Decrypt(Encrypt(%d)) = %d; want %d", pt, back, pt)
		}
	}
}

// TestOutOfRange tests that encrypting a value outside the input range returns an error
func TestOutOfRange(t *testing.T) {
	ope, _ := NewOPE(defaultKey, nil, nil)
	_, err := ope.Encrypt(int64(-1))
	if err != ErrOutOfRange {
		t.Fatalf("Encrypt(-1) expected error %v, got %v", ErrOutOfRange, err)
	}
	_, err = ope.Encrypt(32768)
	if err != ErrOutOfRange {
		t.Fatalf("Encrypt(32768) expected error %v, got %v", ErrOutOfRange, err)
	}
}

// TestDifferentKeysYieldDifferentCiphertexts tests that using a different key produces different ciphertexts for the same plaintext
func TestDifferentKeysYieldDifferentCiphertexts(t *testing.T) {
	key1 := []byte("\x12\x23\x34\x45\x56\x67\x78\x89\x90\x0A\xAB\xBC\xCD\xDE\xEF\xF0\x13\x14\x15\x16\x17\x18\x19\x20\x21\x22\x23\x24\x25\x26\x27\x28")
	key2 := []byte("\x0A\xAB\xBC\xCD\xDE\xEF\xF0\x13\x14\x15\x16\x12\x23\x34\x45\x56\x67\x78\x89\x90\x12\x13\x14\x15\x16\x17\x18\x19\x20\x21\x22\x23")
	ope1, _ := NewOPE(key1, nil, nil)
	ope2, _ := NewOPE(key2, nil, nil)
	for _, pt := range []int64{0, 1, 10, 100, 1000, 2000, 5000} {
		ct1, _ := ope1.Encrypt(pt)
		ct2, _ := ope2.Encrypt(pt)
		if ct1 == ct2 {
			t.Fatalf("Encrypt(%d) produced same ciphertext %d for different keys", pt, ct1)
		}
	}
}

// TestSmallOutputRange tests that when the output range is only slightly larger than the input range, the ciphertexts are still unique and order-preserving
func TestSmallOutputRange(t *testing.T) {
	in, _ := NewValueRange(0, 2)
	out, _ := NewValueRange(2, 5)
	ope, err := NewOPE(smallKey, &in, &out)
	if err != nil {
		t.Fatalf("Failed to create OPE cipher: %v", err)
	}
	for _, pt := range []int64{0, 1, 2} {
		ct, err := ope.Encrypt(pt)
		if err != nil {
			t.Fatalf("Encrypt(%d) returned error: %v", pt, err)
		}
		if !out.Contains(ct) {
			t.Fatalf("Encrypt(%d) = %d is outside output range", pt, ct)
		}
		got, err := ope.Decrypt(ct)
		if err != nil {
			t.Fatalf("Decrypt(%d) returned error: %v", ct, err)
		}
		if got != pt {
			t.Fatalf("Decrypt(Encrypt(%d)) = %d; want %d", pt, got, pt)
		}
	}
}

// TestBigRanges tests that the cipher can handle very large ranges above 2^32
func TestBigRanges(t *testing.T) {
	in, _ := NewValueRange(1<<32, 1<<33)
	out, _ := NewValueRange(1<<48, 1<<49)
	ope, err := NewOPE(smallKey, &in, &out)
	if err != nil {
		t.Fatalf("Failed to create OPE cipher: %v", err)
	}
	for pt := in.Start; pt <= in.End; pt += 1 << 24 {
		ct, err := ope.Encrypt(pt)
		if err != nil {
			t.Fatalf("Encrypt(%d) returned error: %v", pt, err)
		}
		if !out.Contains(ct) {
			t.Fatalf("Encrypt(%d) = %d is outside output range", pt, ct)
		}
		got, err := ope.Decrypt(ct)
		if err != nil {
			t.Fatalf("Decrypt(%d) returned error: %v", ct, err)
		}
		if got != pt {
			t.Fatalf("Decrypt(Encrypt(%d)) = %d; want %d", pt, got, pt)
		}
	}
}

// TestInvalidRangeRejected tests that NewOPE returns an error when the output range is smaller than the input range
func TestInvalidRangeRejected(t *testing.T) {
	in, _ := NewValueRange(0, 10)
	out, _ := NewValueRange(1, 2)
	_, err := NewOPE(smallKey, &in, &out)
	if err != ErrInvalidRanges {
		t.Fatalf("Expected error %v when output range is smaller than input range, got %v", ErrInvalidRanges, err)
	}
}

// TestOrderPreservedExhaustive tests that for a small range (0..9), the ciphertexts are in the same order as the plaintexts
func TestOrderPreservedExhaustive(t *testing.T) {
	in, _ := NewValueRange(0, 63)
	out, _ := NewValueRange(0, 4095)
	ope, _ := NewOPE(defaultKey, &in, &out)
	prev, err := ope.Encrypt(in.Start)
	if err != nil {
		t.Fatalf("Encrypt(%d) returned error: %v", in.Start, err)
	}
	for pt := int64(1); pt <= 63; pt++ {
		ct, err := ope.Encrypt(pt)
		if err != nil {
			t.Fatalf("Encrypt(%d) returned error: %v", pt, err)
		}
		if ct <= prev {
			t.Fatalf("Encrypt(%d) = %d is not greater than previous ciphertext %d", pt, ct, prev)
		}
		prev = ct
	}
}

// TestSampleHGDMonotone checks that Encrypt produces monotone increasing ciphertexts for monotone increasing plaintexts, for a variety of input and output ranges and patterns of coins used in the hypergeometric sampling
func TestSampleHGDMonotone(t *testing.T) {
	key := []byte("test-key-16bytes")
	inR := ValueRange{0, 15}
	outR := ValueRange{0, 255}
	ope, err := NewOPE(key, &inR, &outR)
	if err != nil {
		t.Fatalf("NewOPE(...) returned error: %v", err)
	}

	prev := outR.Start - 1
	for v := inR.Start; v <= inR.End; v++ {
		got, err := ope.Encrypt(v)
		if err != nil {
			t.Fatalf("Encrypt(%d) returned error: %v", v, err)
		}
		if got < prev {
			t.Fatalf("Encrypt(%d) = %d, which is less than Encrypt(%d) = %d", v, got, v-1, prev)
		}
		prev = got
	}
}
