package goope

import (
	"math"
	"sort"
	"testing"
)

var defaultKey = []byte("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA") // 32 × 'A'
var smallKey = []byte("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")   // 32 × 'B'

// TestEncryptMatchesPython verifies our output matches the Python reference implementation exactly, using the same key and default ranges.
func TestEncryptMatchesPython(t *testing.T) {
	cipher, err := NewOPE(defaultKey, nil, nil)
	if err != nil {
		t.Fatal(err)
	}

	// Expected values generated by Python reference implementation.
	tests := []struct {
		plaintext  int
		ciphertext int
	}{
		{0, 220331},
		{1, 276895},
		{100, 6687907},
		{500, 30565337},
		{1000, 60687481},
		{5000, 318247430},
		{32767, 2147273337},
	}

	for _, tt := range tests {
		got, err := cipher.Encrypt(tt.plaintext)
		if err != nil {
			t.Errorf("Encrypt(%d): unexpected error: %v", tt.plaintext, err)
			continue
		}
		if got != tt.ciphertext {
			t.Errorf("Encrypt(%d) = %d, want %d", tt.plaintext, got, tt.ciphertext)
		}
	}
}

// TestDecryptRoundTrip tests that decrypt(encrypt(x)) == x for all tests values
func TestDecryptRoundTrip(t *testing.T) {
	inRange := ValueRange{Start: -1000, End: int(math.Pow(2, 20))}
	outRange := ValueRange{Start: -10000, End: int(math.Pow(2, 32))}
	ope, err := NewOPE(defaultKey, &inRange, &outRange)
	if err != nil {
		t.Fatalf("Failed to create OPE cipher: %v", err)
	}

	for _, pt := range []int{-1000, -100, -20, -1, 0, 1, 10, 100, 314, 1337, 1338, 10000} {
		ct, err := ope.Encrypt(pt)
		if err != nil {
			t.Fatalf("Encrypt(%d) returned error: %v", pt, err)
		}
		got, err := ope.Decrypt(ct)
		if err != nil {
			t.Fatalf("Decrypt(%d) returned error: %v", ct, err)
		}
		if got != pt {
			t.Fatalf("Decrypt(Encrypt(%d)) = %d; want %d", pt, got, pt)
		}
	}
}

// TestOrderPreserved tests that the order of plaintexts is preserved in the ciphertexts.
func TestOrderPreserved(t *testing.T) {
	ope, err := NewOPE(defaultKey, nil, nil)
	if err != nil {
		t.Fatalf("Failed to create OPE cipher: %v", err)
	}

	plaintexts := []int{0, 1, 2, 10, 28, 42, 1000, 1001, int(math.Pow(2, 15) - 1)}
	ciphertexts := make([]int, len(plaintexts))
	for i, pt := range plaintexts {
		ct, err := ope.Encrypt(pt)
		if err != nil {
			t.Fatalf("Encrypt(%d) returned error: %v", pt, err)
		}
		ciphertexts[i] = ct
	}

	if !sort.IntsAreSorted(ciphertexts) {
		t.Fatalf("Ciphertexts are not in sorted order: %v", ciphertexts)
	}
}

// TestDeterministic tests that encrypting the same plaintext multiple times yields the same ciphertext.
func TestDeterministic(t *testing.T) {
	ope, err := NewOPE(defaultKey, nil, nil)
	if err != nil {
		t.Fatalf("Failed to create OPE cipher: %v", err)
	}
	plaintexts := []int{0, 314, 1337, 1338, 10000}
	for _, pt := range plaintexts {
		ct1, err := ope.Encrypt(pt)
		if err != nil {
			t.Fatalf("Encrypt(%d) returned error: %v", pt, err)
		}
		ct2, err := ope.Encrypt(pt)
		if err != nil {
			t.Fatalf("Encrypt(%d) returned error: %v", pt, err)
		}
		if ct1 != ct2 {
			t.Fatalf("Encrypt(%d) returned different ciphertexts: %d and %d", pt, ct1, ct2)
		}
	}
}

// TestDenseRange tests that equal ranges (0..32768) yield 1-1 mappings
func TestDenseRange(t *testing.T) {
	rangeStart := 0
	rangeEnd := math.Pow(2, 15)
	inRange := ValueRange{Start: rangeStart, End: int(rangeEnd)}
	outRange := inRange.Copy()
	ope, err := NewOPE(defaultKey, &inRange, &outRange)
	if err != nil {
		t.Fatalf("Failed to create OPE cipher: %v", err)
	}
	plaintexts := []int{0, 10, 20, 50, 100, 1000, int(math.Pow(2, 10)), int(math.Pow(2, 15))}
	for _, pt := range plaintexts {
		ct, err := ope.Encrypt(pt)
		if err != nil {
			t.Fatalf("Encrypt(%d) returned error: %v", pt, err)
		}
		got, err := ope.Decrypt(ct)
		if err != nil {
			t.Fatalf("Decrypt(%d) returned error: %v", ct, err)
		}
		if got != pt {
			t.Fatalf("Decrypt(Encrypt(%d)) = %d; want %d", pt, got, pt)
		}
	}
}

// TestCustomRanges verifies behavior when a small custom range is used (0..9 -> 0..99)
func TestCustomRanges(t *testing.T) {
	in, _ := NewValueRange(0, 9)
	out, _ := NewValueRange(0, 99)
	ope, err := NewOPE(smallKey, &in, &out)
	if err != nil {
		t.Fatalf("Failed to create OPE cipher: %v", err)
	}

	// Expected values generated by Python reference implementation.
	expected := []int{17, 46, 59, 64, 68, 77, 81, 84, 90, 91}
	for pt, want := range expected {
		got, err := ope.Encrypt(pt)
		if err != nil {
			t.Errorf("Encrypt(%d) returned error: %v", pt, err)
			continue
		}
		if got != want {
			t.Fatalf("Encrypt(%d) = %d; want %d", pt, got, want)
		}
		// also verify round-trip
		back, err := ope.Decrypt(got)
		if err != nil {
			t.Errorf("Decrypt(%d) returned error: %v", got, err)
			continue
		}
		if back != pt {
			t.Fatalf("Decrypt(Encrypt(%d)) = %d; want %d", pt, back, pt)
		}
	}
}

// TestOutOfRange tests that encrypting a value outside the input range returns an error
func TestOutOfRange(t *testing.T) {
	ope, _ := NewOPE(defaultKey, nil, nil)
	_, err := ope.Encrypt(-1)
	if err != ErrOutOfRange {
		t.Fatalf("Encrypt(-1) expected error %v, got %v", ErrOutOfRange, err)
	}
	_, err = ope.Encrypt(32768)
	if err != ErrOutOfRange {
		t.Fatalf("Encrypt(32768) expected error %v, got %v", ErrOutOfRange, err)
	}
}
